server:
  port: 8002
mybatis:
  base-packages: com.tianqi.movie.dao
  type-aliases-package: com.tianqi.movie.pojo
  mapper-locations: classpath:mapper/*.xml
spring:
  redis:
    host: 47.96.238.166
    password: tq123456
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/Demo

logging:
  level:
    com.tianqi: debug
feign:
  hystrix:
    enabled: false
  httpclient:
    connection-timeout: 30000


hystrix:
  command:
    default:
      fallback:
        enabled: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
client:
  username: demo-movie
  password: 123456