server:
  port: 8002
mybatis-plus:
  # XML mapper文件所在位置
  mapper-locations: classpath:mapper/*.xml
  # POJO包起别名
  type-aliases-package: com.tianqi.movie.pojo
  # 枚举所在包，可以保存枚举的值到数据库，结合@EnumValue使用
  type-enums-package: com.tianqi.common.enums.database
spring:
  application:
    name: @project.artifactId@
  redis:
    host: 127.0.0.1
    password: 123456
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/Demo
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848
      discovery:
        group: dev
        namespace: def2c741-902f-4be8-b173-835204b0f6fd
        ip: 127.0.0.1
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
      filter:
        enabled: true
  boot:
    admin:
      client:
        url: http://127.0.0.1:9091
        instance:
          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.tianqi: debug
feign:
  httpclient:
    connection-timeout: 30000


client:
  username: demo-movie
  password: 123456
