server:
  port: 8000
mybatis-plus:
  type-aliases-package: com.tianqi.gateway.pojo
  mapper-locations: classpath:mapper/*.xml
  type-enums-package: com.tianqi.auth.enums
spring:
  application:
    name: @project.artifactId@
  redis:
    host: 127.0.0.1
    password: 123456
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/Demo
  profiles:
    active: dev
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848
      discovery:
        group: dev
        namespace: def2c741-902f-4be8-b173-835204b0f6fd
    gateway:
      routes:
        - id: project-auth-service
          uri: lb://project-auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
          order: 0
        - id: project-movie-service
          uri: lb://project-movie-service
          predicates:
            - Path=/api/movie/**
          filters:
            - StripPrefix=2
          order: 1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    com.tianqi: debug
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 30000


hystrix:
  command:
    default:
      fallback:
        enabled: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
client:
  username: demo-gateway
  password: 123456

