server:
  port: 8001
mybatis-plus:
  type-aliases-package: com.tianqi.auth.pojo
  mapper-locations: classpath:mapper/*.xml
  type-enums-package: com.tianqi.common.enums
spring:
  application:
    name: @project.artifactId@
  redis:
    host: 47.96.238.166
    password: tq123456
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tianqi_project
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        group: dev
        namespace: def2c741-902f-4be8-b173-835204b0f6fd
      username: nacos
      password: nacos
logging:
  level:
    com.tianqi: debug
feign:
  hystrix:
    enabled: false
  httpclient:
    connection-timeout: 30000


hystrix:
  command:
    default:
      fallback:
        enabled: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
client:
  username: demo-auth
  password: 123456