server:
  port: 8001
mybatis-plus:
  type-aliases-package: com.tianqi.auth.pojo
  mapper-locations: classpath:mapper/*.xml
  type-enums-package: com.tianqi.common.enums
  type-handlers-package: com.tianqi.common.handler.type

spring:
  application:
    name: @project.artifactId@
  redis:
    host: 127.0.0.1
    password: 123456
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tianqi_auth
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        group: dev
        namespace: def2c741-902f-4be8-b173-835204b0f6fd
      username: nacos
      password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
        port: 8771
        client-ip: 127.0.0.1
      filter:
        enabled: true
        order: -1999999999
logging:
  level:
    com.tianqi: debug
feign:
  httpclient:
    connection-timeout: 30000
    read-timeout: 30000
  sentinel:
    enabled: true



client:
  username: demo-auth
  password: 123456

tq:
  sentinel:
    nacos:
      address: 127.0.0.1:8848
      namespace: def2c741-902f-4be8-b173-835204b0f6fd
      group-id: dev
      username: nacos
      password: nacos